import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import './style.css';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || '';
const supabase = SUPABASE_URL && SUPABASE_ANON_KEY ? createClient(SUPABASE_URL,SUPABASE_ANON_KEY) : null;
const demo = {tasks:[],people:[],requirements:[],assignments:[],payments:[]};
let state={page:'dashboard', selectedTask:null, data:demo, loading:false};

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const toast=(m,type='ok')=>{const x=document.createElement('div');x.className='toast '+type;x.textContent=m;document.body.appendChild(x);setTimeout(()=>x.remove(),2800)};

async function db(table,method='select',payload=null,id=null){
 if(!supabase) { console.error('Supabase client not configured'); return null; }
 let q=supabase.from(table); if(method==='select') return (await q.select('*').order('created_at',{ascending:false})).data||[];
 if(method==='insert'){const r=await q.insert(payload).select().single();if(r.error) console.error('SUPABASE INSERT ERROR:',r.error);return r.data;}
 if(method==='update') return (await q.update(payload).eq('id',id).select().single()).data;
}
async function load(){
 if(!supabase){render();return}
 state.loading=true;render();
 const tables=['tasks','people','part_time_requirements','assignments','payments'];
 const out=await Promise.all(tables.map(t=>db(t)));
 state.data={tasks:out[0]||[],people:out[1]||[],requirements:out[2]||[],assignments:out[3]||[],payments:out[4]||[]};state.loading=false;render();
}
const nav=[['dashboard','▦','Dashboard'],['tasks','✓','Tasks'],['requirements','◫','Part-Time Requirements'],['people','♙','People'],['assignments','↗','Assignments'],['payments','₹','Payments']];
function layout(content){return `<div class="shell"><aside><div class="brand"><span>TF</span><div><b>TaskFlow</b><small>V1 Admin</small></div></div><nav>${nav.map(n=>`<button class="nav ${state.page===n[0]?'active':''}" data-page="${n[0]}"><i>${n[1]}</i>${n[2]}</button>`).join('')}</nav><div class="sidefoot">Admin controlled<br/><small>Task → Requirement → Person → Assignment</small></div></aside><main><header><div><div class="eyebrow">OPERATIONS</div><h1>${nav.find(n=>n[0]===state.page)?.[2]||'Dashboard'}</h1></div><button class="primary" data-action="new-task">+ New Task</button></header>${content}</main></div>`}
function dashboard(){const d=state.data,t=d.tasks||[];return `<section class="cards"><div class="card"><small>Total Tasks</small><strong>${t.length}</strong></div><div class="card"><small>In Progress</small><strong>${t.filter(x=>x.status==='In Progress').length}</strong></div><div class="card"><small>Completed</small><strong>${t.filter(x=>x.status==='Completed').length}</strong></div><div class="card"><small>Pending Payments</small><strong>${money((d.payments||[]).filter(x=>x.payment_status==='Pending').reduce((a,x)=>a+Number(x.amount||0),0))}</strong></div></section><section class="grid2"><div class="panel"><div class="panelhead"><h2>Tasks needing attention</h2><button class="link" data-page="tasks">View all</button></div>${t.filter(x=>['Open','Assigned','In Progress'].includes(x.status)).slice(0,6).map(taskrow).join('')||empty('No active tasks')}</div><div class="panel"><div class="panelhead"><h2>Available people</h2><button class="link" data-page="people">View all</button></div>${(d.people||[]).filter(x=>x.status==='Available').slice(0,6).map(personrow).join('')||empty('No available people')}</div></section>`}
function taskrow(x){return `<button class="row" data-task="${x.id}"><div><b>${esc(x.title)}</b><small>${esc(x.task_number||'')} · ${esc(x.location_name||'Online')}</small></div><span class="badge ${String(x.status).toLowerCase().replaceAll(' ','-')}">${esc(x.status)}</span></button>`}
function personrow(x){return `<div class="row static"><div><b>${esc(x.name)}</b><small>${esc(x.location||'')} · ${esc((x.skills||[]).join(', '))}</small></div><span class="dot green">●</span></div>`}
function empty(s){return `<div class="empty">${s}</div>`}
function tasks(){const t=state.data.tasks||[];return `<section class="toolbar"><input id="taskSearch" placeholder="Search tasks…"/><select id="taskFilter"><option value="">All statuses</option>${['Draft','Open','Assigned','In Progress','Completed','On Hold','Cancelled'].map(x=>`<option>${x}</option>`).join('')}</select></section><section class="panel"><div id="taskTable">${tableTasks(t)}</div></section>`}
function tableTasks(t){return `<table><thead><tr><th>Task</th><th>Priority</th><th>Deadline</th><th>Budget</th><th>Status</th></tr></thead><tbody>${t.map(x=>`<tr data-task="${x.id}"><td><b>${esc(x.title)}</b><small>${esc(x.task_number||'')}</small></td><td>${esc(x.priority)}</td><td>${esc(x.deadline||'—')}</td><td>${money(x.budget)}</td><td><span class="badge">${esc(x.status)}</span></td></tr>`).join('')||`<tr><td colspan="5">${empty('No tasks yet')}</td></tr>`}</tbody></table>`}
function requirements(){const r=state.data.requirements||[];return `<section class="toolbar"><button class="primary" data-action="new-requirement">+ New Requirement</button></section><section class="panel"><table><thead><tr><th>Requirement</th><th>Task</th><th>People</th><th>Location</th><th>Payment</th><th>Status</th></tr></thead><tbody>${r.map(x=>`<tr><td><b>${esc(x.title)}</b></td><td>${esc((state.data.tasks.find(t=>t.id===x.task_id)||{}).title||'—')}</td><td>${x.people_required}</td><td>${esc(x.location||'—')}</td><td>${money(x.payment_amount)}</td><td><span class="badge">${esc(x.status)}</span></td></tr>`).join('')||`<tr><td colspan="6">${empty('No requirements yet')}</td></tr>`}</tbody></table></section>`}
function people(){const p=state.data.people||[];return `<section class="toolbar"><button class="primary" data-action="new-person">+ Add Person</button></section><section class="peoplegrid">${p.map(x=>`<div class="person card"><div class="avatar">${esc((x.name||'?')[0].toUpperCase())}</div><h3>${esc(x.name)}</h3><small>${esc(x.location||'')}</small><p>${esc((x.skills||[]).join(' · ')||'No skills added')}</p><span class="badge ${x.status==='Available'?'available':''}">${esc(x.status)}</span></div>`).join('')||empty('No people added')}</section>`}
function assignments(){const a=state.data.assignments||[];return `<section class="panel"><table><thead><tr><th>Task</th><th>Person</th><th>Status</th><th>Payment</th><th>Assigned</th></tr></thead><tbody>${a.map(x=>{const t=state.data.tasks.find(t=>t.id===x.task_id),p=state.data.people.find(p=>p.id===x.person_id);return `<tr><td>${esc(t?.title||'—')}</td><td>${esc(p?.name||'—')}</td><td><span class="badge">${esc(x.status)}</span></td><td>${money(x.agreed_payment)}</td><td>${esc((x.assigned_at||'').slice(0,10))}</td></tr>`}).join('')||`<tr><td colspan="5">${empty('No assignments yet')}</td></tr>`}</tbody></table></section>`}
function payments(){const p=state.data.payments||[];return `<section class="cards"><div class="card"><small>Paid</small><strong>${money(p.filter(x=>x.payment_status==='Paid').reduce((a,x)=>a+Number(x.amount||0),0))}</strong></div><div class="card"><small>Pending</small><strong>${money(p.filter(x=>x.payment_status==='Pending').reduce((a,x)=>a+Number(x.amount||0),0))}</strong></div></section><section class="panel"><table><thead><tr><th>Person</th><th>Task</th><th>Amount</th><th>Status</th><th>Paid At</th></tr></thead><tbody>${p.map(x=>{const a=state.data.assignments.find(a=>a.id===x.assignment_id),person=state.data.people.find(p=>p.id===x.person_id),task=state.data.tasks.find(t=>t.id===a?.task_id);return `<tr><td>${esc(person?.name||'—')}</td><td>${esc(task?.title||'—')}</td><td>${money(x.amount)}</td><td><span class="badge">${esc(x.payment_status)}</span></td><td>${esc((x.paid_at||'').slice(0,10)||'—')}</td></tr>`}).join('')||`<tr><td colspan="5">${empty('No payments yet')}</td></tr>`}</tbody></table></section>`}
function modal(type){if(type==='task')return `<div class="modal"><form id="taskForm" class="form"><div class="modalhead"><h2>Create Task</h2><button type="button" data-close>×</button></div><label>Task title<input name="title" required maxlength="120"/></label><label>Description<textarea name="description" required maxlength="2000"></textarea></label><div class="formgrid"><label>Category<input name="category"/></label><label>Priority<select name="priority"><option>Normal</option><option>Low</option><option>High</option><option>Urgent</option></select></label><label>Location<input name="location_name"/></label><label>Mode<select name="online_or_offline"><option>Offline</option><option>Online</option><option>Hybrid</option></select></label><label>Start date<input type="date" name="start_date"/></label><label>Deadline<input type="date" name="deadline" required/></label><label>Estimated hours<input type="number" min="0" step="0.5" name="estimated_hours"/></label><label>Budget ₹<input type="number" min="0" step="0.01" name="budget" required/></label></div><div class="modalactions"><button type="button" data-close>Cancel</button><button class="primary">Create Task</button></div></form></div>`;
if(type==='person')return `<div class="modal"><form id="personForm" class="form"><div class="modalhead"><h2>Add Person</h2><button type="button" data-close>×</button></div><label>Name<input name="name" required maxlength="100"/></label><div class="formgrid"><label>Phone<input name="phone"/></label><label>Email<input type="email" name="email"/></label><label>Location<input name="location"/></label><label>Status<select name="status"><option>Available</option><option>Busy</option><option>Inactive</option><option>Blocked</option></select></label></div><label>Skills <input name="skills" placeholder="delivery, data entry, errands"/></label><label>Availability<input name="availability" placeholder="2 PM – 7 PM"/></label><label>Notes<textarea name="notes"></textarea></label><div class="modalactions"><button type="button" data-close>Cancel</button><button class="primary">Save Person</button></div></form></div>`;
return `<div class="modal"><form id="reqForm" class="form"><div class="modalhead"><h2>Create Part-Time Requirement</h2><button type="button" data-close>×</button></div><label>Task<select name="task_id" required>${state.data.tasks.map(t=>`<option value="${t.id}">${esc(t.task_number)} — ${esc(t.title)}</option>`).join('')}</select></label><label>Requirement title<input name="title" required/></label><div class="formgrid"><label>People required<input type="number" min="1" value="1" name="people_required" required/></label><label>Location<input name="location"/></label><label>Start date<input type="date" name="start_date"/></label><label>End date<input type="date" name="end_date"/></label><label>Start time<input type="time" name="start_time"/></label><label>End time<input type="time" name="end_time"/></label><label>Payment type<select name="payment_type"><option>Per task</option><option>Per hour</option><option>Per day</option></select></label><label>Payment amount ₹<input type="number" min="0" step="0.01" name="payment_amount" required/></label></div><label>Required skills<input name="skills_required" placeholder="delivery, communication"/></label><label>Additional requirements<textarea name="requirements"></textarea></label><div class="modalactions"><button type="button" data-close>Cancel</button><button class="primary">Create Requirement</button></div></form></div>`}
function taskDetail(id){const t=state.data.tasks.find(x=>x.id===id);if(!t)return '';const req=state.data.requirements.find(x=>x.task_id===id);const as=state.data.assignments.filter(x=>x.task_id===id);return `<div class="detail"><button class="link" data-page="tasks">← Back to tasks</button><div class="detailhead"><div><span class="badge">${esc(t.status)}</span><h2>${esc(t.title)}</h2><p>${esc(t.description)}</p></div><div class="actions"><button data-action="status" data-id="${t.id}">Change status</button>${t.status!=='Completed'?'<button class="primary" data-action="assign" data-id="'+t.id+'">Assign person</button>':''}</div></div><section class="cards"><div class="card"><small>Task ID</small><strong>${esc(t.task_number)}</strong></div><div class="card"><small>Deadline</small><strong>${esc(t.deadline||'—')}</strong></div><div class="card"><small>Budget</small><strong>${money(t.budget)}</strong></div><div class="card"><small>Location</small><strong>${esc(t.location_name||'Online')}</strong></div></section><section class="grid2"><div class="panel"><h2>Requirement</h2>${req?`<p><b>${esc(req.title)}</b></p><p>${req.people_required} person(s) · ${esc((req.skills_required||[]).join(', '))}</p><p>${money(req.payment_amount)} · ${esc(req.location||'')}</p>`:empty('No requirement created')}</div><div class="panel"><h2>Assignments</h2>${as.map(a=>{const p=state.data.people.find(p=>p.id===a.person_id);return `<div class="row static"><div><b>${esc(p?.name||'Unknown')}</b><small>${esc(a.status)}</small></div><button data-action="assignment-status" data-id="${a.id}">Update</button></div>`}).join('')||empty('No one assigned')}</div></section></div>`}
function render(){let c=state.page==='dashboard'?dashboard():state.page==='tasks'?tasks():state.page==='requirements'?requirements():state.page==='people'?people():state.page==='assignments'?assignments():payments();if(state.selectedTask)c=taskDetail(state.selectedTask);document.querySelector('#app').innerHTML=layout(c);}
function openModal(t){document.body.insertAdjacentHTML('beforeend',modal(t))}
async function save(form,table){const fd=new FormData(form),o=Object.fromEntries(fd.entries());if(table==='tasks'){o.budget=Number(o.budget||0);o.estimated_hours=Number(o.estimated_hours||0);o.status='Open';o.task_number='TASK-'+String((state.data.tasks.length||0)+1).padStart(5,'0');o.category_id=null;o.created_by=null;}if(table==='people'){o.skills=o.skills?o.skills.split(',').map(s=>s.trim()).filter(Boolean):[];}if(table==='part_time_requirements'){o.people_required=Number(o.people_required);o.payment_amount=Number(o.payment_amount);o.skills_required=o.skills_required?o.skills_required.split(',').map(s=>s.trim()).filter(Boolean):[];o.status='Open';}let x=await db(table,'insert',o);if(!x){x={...o,id:crypto.randomUUID(),created_at:new Date().toISOString()};const key=table==='part_time_requirements'?'requirements':table;state.data[key].unshift(x);}else{const key=table==='part_time_requirements'?'requirements':table;state.data[key].unshift(x)}document.querySelector('.modal')?.remove();toast('Saved successfully');render();}
async function assign(id){const people=state.data.people.filter(p=>p.status==='Available');if(!people.length){toast('No available people','err');return}const choices=people.map((p,i)=>`${i+1}. ${p.name} — ${p.location||'No location'} — ${(p.skills||[]).join(', ')}`).join('\n');const n=prompt('Select person by number:\n'+choices);const p=people[Number(n)-1];if(!p)return;const req=state.data.requirements.find(r=>r.task_id===id);const payload={task_id:id,requirement_id:req?.id||null,person_id:p.id,status:'Pending',agreed_payment:req?.payment_amount||state.data.tasks.find(t=>t.id===id)?.budget||0,assigned_at:new Date().toISOString()};let x=await db('assignments','insert',payload);if(!x)x={...payload,id:crypto.randomUUID()};state.data.assignments.unshift(x);await db('tasks','update',{status:'Assigned'},id);const t=state.data.tasks.find(t=>t.id===id);if(t)t.status='Assigned';p.status='Busy';toast(`${p.name} assigned`);render()}

document.addEventListener('click',async e=>{const nav=e.target.closest('[data-page]');if(nav){state.page=nav.dataset.page;state.selectedTask=null;render();return}const tr=e.target.closest('[data-task]');if(tr){state.selectedTask=tr.dataset.task;render();return}if(e.target.matches('[data-close]')){e.target.closest('.modal')?.remove();return}const a=e.target.closest('[data-action]');if(!a)return;const act=a.dataset.action;if(act==='new-task')openModal('task');if(act==='new-person')openModal('person');if(act==='new-requirement')openModal('requirement');if(act==='assign')assign(a.dataset.id);if(act==='status'){const opts=['Open','Assigned','In Progress','Completed','On Hold','Cancelled'];const n=prompt('Enter new status:\n'+opts.join(', '));if(opts.includes(n)){const t=state.data.tasks.find(x=>x.id===a.dataset.id);t.status=n;await db('tasks','update',{status:n},t.id);render();}}if(act==='assignment-status'){const n=prompt('Enter assignment status: Pending, Accepted, Rejected, In Progress, Completed, Cancelled');const ok=['Pending','Accepted','Rejected','In Progress','Completed','Cancelled'];if(ok.includes(n)){const x=state.data.assignments.find(x=>x.id===a.dataset.id);x.status=n;await db('assignments','update',{status:n},x.id);render();}}});
document.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='taskForm')save(e.target,'tasks');if(e.target.id==='personForm')save(e.target,'people');if(e.target.id==='reqForm')save(e.target,'part_time_requirements')});
document.addEventListener('input',e=>{if(e.target.id==='taskSearch'){const q=e.target.value.toLowerCase();const f=document.querySelector('#taskFilter')?.value||'';const t=state.data.tasks.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!f||x.status===f));const box=document.querySelector('#taskTable');if(box)box.innerHTML=tableTasks(t)}});document.addEventListener('change',e=>{if(e.target.id==='taskFilter'){const q=document.querySelector('#taskSearch')?.value.toLowerCase()||'';const f=e.target.value;const t=state.data.tasks.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!f||x.status===f));document.querySelector('#taskTable').innerHTML=tableTasks(t)}});
load();
  
